name: wclient
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: teja <email@example.com>

environment:
  sdk: '>=2.1.1 <3.0.0'

dependencies:
  angular:
  common:
    path: ../common
  player:
    path: ../player
  angular_color_picker: ^1.0.2

dev_dependencies:
  build_runner:
  build_web_compilers:
  # angular_analyzer_plugin:
  analyzer:

dependency_overrides:
  angular_color_picker:
    path: ../../dart/angular_color_picker
  lib_colors:
    path: ../../dart/lib_colors